// Light app defaults from pixii-ai-app-frontend production cda4a4ae.
// Capsule controls are the approved B variant (the app's AsinEntry treatment).
// Keep these scoped so developer, notice and denial pages are not redesigned.
export const APP_THEME_STYLES = `
@font-face{font-family:'Cabinet Grotesk';src:url('/assets/app-theme/v1/CabinetGrotesk-Medium.woff2') format('woff2');font-style:normal;font-weight:500;font-display:swap}
@font-face{font-family:Switzer;src:url('/assets/app-theme/v1/Switzer-Regular.woff2') format('woff2');font-style:normal;font-weight:400;font-display:swap}
@font-face{font-family:Switzer;src:url('/assets/app-theme/v1/Switzer-Medium.woff2') format('woff2');font-style:normal;font-weight:500;font-display:swap}
body.app-theme{--surface:#f9fafb;--surface:oklch(.985 .002 240);--orange:#d65a31;--orange:oklch(.62 .166 38.2);--ink:#090a0c;--ink:oklch(.145 .004 240);--muted:#6b7379;--muted:oklch(.55 .014 240);--line:#e4e6e8;--line:oklch(.925 .003 240);--input:#dcdee0;--input:oklch(.9 .004 240);--green:#298333;--green:oklch(.5 .16 145);background:var(--surface);color:var(--ink);font-family:Switzer,ui-sans-serif,system-ui,sans-serif;font-weight:400;letter-spacing:.024em;line-height:1.5;padding:max(40px,env(safe-area-inset-top)) max(24px,env(safe-area-inset-right)) max(32px,env(safe-area-inset-bottom)) max(24px,env(safe-area-inset-left))}
.app-theme main{width:min(100%,440px)}
.app-theme h1,.app-theme h2{font-family:'Cabinet Grotesk',ui-sans-serif,system-ui,sans-serif;font-weight:500;letter-spacing:-.025em;line-height:1.12;text-wrap:balance}
.app-theme .signup-header{margin-bottom:28px}.app-theme .signup-title{font-size:clamp(28px,7.6vw,36px);max-width:none}
.app-theme .sponsor{font-size:12px;line-height:1.4;gap:7px;margin:0 0 24px;letter-spacing:0;color:var(--muted)}.app-theme .sponsor .logo{width:86px;margin:0}
.app-theme .field{margin-bottom:20px}.app-theme .field-label{font-size:14px;font-weight:500;line-height:1.4;margin-bottom:8px;letter-spacing:0}.app-theme .required-marker{font-weight:500;color:var(--error)}
.app-theme input[type=text],.app-theme input[type=email],.app-theme input[type=tel],.app-theme select{background:var(--surface);border:1px solid var(--input);border-radius:999px;min-height:48px;font:inherit;font-size:16px;padding:11px 18px;transition:border-color .15s ease,box-shadow .15s ease}
.app-theme input::placeholder{color:var(--muted)}.app-theme input:focus-visible,.app-theme select:focus-visible,.app-theme button:focus-visible,.app-theme a:focus-visible{outline:2px solid var(--orange);outline-offset:3px}
.app-theme .phone-control{background:var(--surface);border:1px solid var(--input);border-radius:999px;min-height:48px}.app-theme .phone-control:focus-within{outline:2px solid var(--orange);outline-offset:3px}.app-theme .phone-control select{background:transparent url('/assets/app-theme/v1/chevron-down.svg') no-repeat right 9px center/16px 16px;border:0;flex-basis:106px;font-size:14px;font-weight:400;min-height:46px;padding:10px 28px 10px 17px}.app-theme .phone-control input{background:transparent;border:0;min-height:46px;padding-left:8px}.app-theme .phone-control input:focus-visible,.app-theme .phone-control select:focus-visible{outline:0}
.app-theme input[aria-invalid=true],.app-theme select[aria-invalid=true],.app-theme .phone-control:has([aria-invalid=true]){border-color:var(--error);box-shadow:inset 0 0 0 1px var(--error)}.app-theme .phone-control input[aria-invalid=true]{box-shadow:none}.app-theme .phone-help{display:block;color:var(--muted);font-size:12px;line-height:1.5;margin-top:7px;letter-spacing:0}
.app-theme .consent-row{gap:12px;margin:24px 0;min-height:44px}.app-theme .consent-copy{font-size:14px;line-height:1.5;letter-spacing:0;color:var(--muted)}.app-theme .consent-row input{appearance:none;width:20px;height:20px;margin:2px 0 0;border:1px solid var(--input);border-radius:5px;background:var(--surface);cursor:pointer}.app-theme .consent-row input:checked{background:var(--orange) url('/assets/app-theme/v1/check.svg') no-repeat center/16px 16px;border-color:var(--orange)}
.app-theme button,.app-theme .button,.app-theme .arrow-cta{border:0;border-radius:999px;background:var(--orange);color:#fff;font-size:16px;font-weight:500;letter-spacing:0;min-height:48px;transition:background-color .15s ease,opacity .15s ease}.app-theme button:hover,.app-theme .button:hover,.app-theme .arrow-cta:hover{background:var(--orange);opacity:.9}.app-theme button:disabled{opacity:.5}
.app-theme .links{margin-top:16px;color:var(--muted);font-size:12px;letter-spacing:0}.app-theme .links span{margin:0 7px}
.app-theme .error{font-weight:400;letter-spacing:0}
.app-theme .status.online{min-height:0;display:block;text-align:left;padding-top:8px}.app-theme .online .connection-state{display:flex;align-items:center;gap:12px;font-size:22px;font-weight:500;letter-spacing:-.02em;margin:0 0 32px!important;line-height:1.3}.app-theme .online .status-dot.is-connected{height:30px;width:30px;flex:none;color:var(--green);background:none;box-shadow:none;border-radius:0}
.app-theme .online .connection-state:focus{outline:none}
.app-theme .online h1{font-size:clamp(30px,8vw,38px);max-width:16ch;line-height:1.1}.app-theme .online .online-subtitle{font-size:16px;line-height:1.5;margin:12px 0 0;color:var(--muted)}
.app-theme .online-action{margin-top:24px}.app-theme .arrow-cta{display:flex;justify-content:center;align-items:center;gap:12px;margin:0;padding:13px 20px;min-height:52px;text-decoration:none}.app-theme .cta-copy{font:inherit;font-size:16px;line-height:1.5;letter-spacing:0}.app-theme .cta-arrow{width:22px;height:22px;flex:none}.app-theme .online .cta-note{font-size:14px;line-height:1.5;margin:12px 0 0;color:var(--muted);letter-spacing:0}
.app-theme .online .redirect-note{font-size:13px;line-height:1.5;margin:24px 0 10px;color:var(--muted);letter-spacing:0}.app-theme .cta-progress{position:static;height:3px;background:var(--line);border-radius:999px;overflow:hidden}.app-theme .cta-progress[hidden]{display:none}.app-theme .cta-progress span{background:#92999e}
.app-theme .online .browser-fallback button{background:none;color:var(--ink)}
@media(min-width:701px) and (min-height:501px){body.app-theme{padding-top:64px}}
@media(max-width:359px){body.app-theme{padding-left:20px;padding-right:20px;padding-top:28px}.app-theme .phone-control select{flex-basis:100px;padding-left:14px}.app-theme .consent-copy{font-size:13px}}
@media(max-height:500px) and (orientation:landscape){body.app-theme{padding-top:24px}.app-theme .online .connection-state{margin-bottom:20px!important}.app-theme .online-action{margin-top:20px}}
`;
