const ASSET = "/assets/flybyjing/v1/";
export const CONNECTING_STYLES = `
body.app-theme.flyby-ad{padding:0}.flyby-ad main{width:100%;max-width:none;margin:0}
.flyby-experience{height:100vh;height:100svh;min-height:240px;display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:var(--surface);color:var(--ink);overflow:hidden;max-width:1280px;margin:0 auto}
.flyby-header{padding:max(32px,env(safe-area-inset-top)) max(32px,env(safe-area-inset-right)) 12px max(32px,env(safe-area-inset-left));text-align:left}
.flyby-header .connection-state{display:flex;align-items:center;margin:0 0 24px!important;color:var(--ink)!important;font-size:16px;font-weight:400;letter-spacing:0;gap:9px;line-height:1.4}.flyby-header .status-dot{background:var(--green);height:9px;width:9px;margin:0;flex:none;box-shadow:none}
.flyby-header .flyby-tagline{font-size:clamp(28px,3.6vw,40px);line-height:1.15;margin:0;white-space:nowrap}.flyby-tagline strong{font-weight:500;color:var(--orange)}.flyby-subtitle{margin:8px 0 0;font-size:16px;color:var(--muted);letter-spacing:0;line-height:1.5}
.flyby-header #status-message{text-align:left}
.flyby-stage{position:relative;min-height:0;isolation:isolate;background:var(--surface)}
.flyby-scene{position:absolute;inset:0;opacity:0;visibility:hidden;transition:opacity .35s ease,visibility .35s;pointer-events:none;padding:12px max(32px,env(safe-area-inset-right)) 12px max(32px,env(safe-area-inset-left));display:flex;align-items:center;justify-content:center}.flyby-scene.is-active{opacity:1;visibility:visible;z-index:1}
.flyby-scene img{display:block;object-fit:contain;max-width:100%;max-height:100%;height:auto}
.flyby-listing-layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(0,3fr);align-items:center;gap:12px;height:100%;width:100%;max-width:1640px}
.flyby-hero{min-height:0;min-width:0;height:100%;display:flex;align-items:center;justify-content:center}.flyby-hero img{width:100%;height:100%;object-fit:contain}
.flyby-thumbnails{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));grid-template-rows:repeat(2,minmax(0,1fr));gap:12px;aspect-ratio:3/2;max-height:100%;min-height:0;align-content:center}.flyby-thumbnails img{width:100%;height:100%;aspect-ratio:1;object-fit:contain;min-height:0}
.flyby-aplus-complete{display:block;height:100%!important;width:100%;object-fit:contain}
.flyby-films{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));align-items:center;gap:16px;width:100%;height:100%;max-width:1660px;min-height:0}.flyby-film{position:relative;width:100%;height:100%;min-height:0;display:flex;align-items:center;justify-content:center}.flyby-film img,.flyby-film video{position:absolute;width:100%;height:100%;object-fit:contain}.flyby-film video{opacity:0;transition:opacity .2s}.flyby-film.is-playing video{opacity:1}
.flyby-bottom{background:var(--surface);padding:12px max(32px,env(safe-area-inset-right)) max(24px,env(safe-area-inset-bottom)) max(32px,env(safe-area-inset-left))}.flyby-progress{height:4px;width:100%;background:var(--line);border-radius:999px;overflow:hidden}.flyby-progress span{display:block;width:100%;height:100%;background:var(--orange);transform:scaleX(0);transform-origin:left center}
.flyby-noscript{position:fixed;bottom:max(75px,calc(env(safe-area-inset-bottom) + 68px));left:16px;right:16px;padding:12px;background:var(--surface);color:var(--ink);z-index:5;text-align:center;font-size:.85rem;font-weight:500}
@media(max-width:700px) and (orientation:portrait){.flyby-header{padding:max(32px,env(safe-area-inset-top)) max(24px,env(safe-area-inset-right)) 8px max(24px,env(safe-area-inset-left))}.flyby-header .flyby-tagline{font-size:clamp(26px,7.7vw,34px)}.flyby-stage{container-type:size}.flyby-scene{padding:8px max(24px,env(safe-area-inset-right)) 8px max(24px,env(safe-area-inset-left))}.flyby-listing-layout{grid-template-columns:minmax(0,1fr);grid-template-rows:auto auto;gap:8px;width:min(100%,calc((100cqh - 26px)*.6));height:auto;max-height:100%}.flyby-hero{height:auto;aspect-ratio:1}.flyby-thumbnails{grid-template-columns:repeat(3,minmax(0,1fr));height:auto;aspect-ratio:auto;gap:6px}.flyby-thumbnails img{height:auto}.flyby-films{grid-template-columns:minmax(0,1fr);grid-template-rows:repeat(2,minmax(0,1fr));gap:12px}.flyby-film:first-child{align-self:end}.flyby-film:last-child{align-self:start}.flyby-film{height:auto;aspect-ratio:16/9;max-height:100%}.flyby-bottom{padding-left:max(24px,env(safe-area-inset-left));padding-right:max(24px,env(safe-area-inset-right))}}
@media(max-height:500px) and (orientation:landscape){.flyby-header{padding:max(12px,env(safe-area-inset-top)) max(24px,env(safe-area-inset-right)) 4px max(24px,env(safe-area-inset-left))}.flyby-header .connection-state{margin-bottom:8px!important}.flyby-header .flyby-tagline{font-size:26px}.flyby-subtitle{margin-top:4px;font-size:14px}.flyby-bottom{padding:4px max(24px,env(safe-area-inset-right)) max(12px,env(safe-area-inset-bottom)) max(24px,env(safe-area-inset-left))}.flyby-scene{padding:4px max(24px,env(safe-area-inset-right)) 4px max(24px,env(safe-area-inset-left))}.flyby-listing-layout{grid-template-columns:minmax(0,2fr) minmax(0,3fr);gap:10px}.flyby-thumbnails{gap:6px;height:100%}}
@media(prefers-reduced-motion:reduce){.flyby-scene,.flyby-film video{transition:none}}
`;

export function connectingContent(): string {
  const descriptions = ["Fly By Jing Sichuan Chili Crisp product photo", "Electric Chengdu Street Heat listing", "Fly By Jing Amazon listing image 3", "Fly By Jing Amazon listing image 4", "Fly By Jing listing: Zero Junk All Flavor", "Fly By Jing Amazon listing image 6", "Fly By Jing listing: Uncensored Chengdu Flavor"];
  return `<section class="flyby-experience" id="flyby-ad" aria-label="Pixii creative showcase">
<header class="flyby-header"><p class="connection-state"><span class="status-dot" aria-hidden="true"></span><span id="status-message" role="status" aria-live="polite">Connecting</span></p><h1 class="flyby-tagline">Pixii designs <strong id="ad-category">Listings</strong></h1><p class="flyby-subtitle" id="ad-subtitle">Create yours in 2 minutes.</p></header>
<div class="flyby-stage">
<section class="flyby-scene flyby-listings is-active" data-scene="listings" aria-label="Seven Amazon listing images" aria-hidden="false"><div class="flyby-listing-layout"><div class="flyby-hero"><img id="ad-first-artwork" src="${ASSET}listing-hero-product.webp" srcset="${ASSET}listing-hero-product-mobile.webp 720w, ${ASSET}listing-hero-product.webp 1280w" sizes="(max-width:700px) 100vw, 40vw" width="1280" height="1280" alt="Fly By Jing Sichuan Chili Crisp product photo" fetchpriority="high" decoding="async"></div><div class="flyby-thumbnails">${descriptions.map((alt, i) => i === 0 ? "" : `<img src="${ASSET}listing-${i + 1}.webp" width="480" height="480" alt="${alt}" decoding="async" fetchpriority="low">`).join("")}</div></div></section>
<section class="flyby-scene flyby-aplus" data-scene="aplus" aria-label="Amazon A+ content" aria-hidden="true"><img class="flyby-aplus-complete" src="${ASSET}aplus-mobile.webp" width="960" height="1565" alt="Fly By Jing complete Amazon A+ design: four panels joined vertically, featuring chili crisp, food, ingredients and benefits" decoding="async" fetchpriority="low"></section>
<section class="flyby-scene flyby-video" data-scene="video" aria-label="Fly By Jing and Bloom video ads" aria-hidden="true"><div class="flyby-films"><div class="flyby-film"><img src="${ASSET}video-poster.webp" width="1280" height="720" alt="Fly By Jing Sichuan Chili Crisp product video still"><video muted playsinline preload="auto" poster="${ASSET}video-poster.webp" aria-label="Fly By Jing product video: chili crisp served over dumplings"><source src="${ASSET}showcase.mp4" type="video/mp4"></video></div><div class="flyby-film"><img src="/assets/bloom/v1/video-poster.webp" width="1280" height="720" alt="Bloom Pop Raspberry Lemonade ad: Only 3g Sugar"><video muted playsinline preload="auto" poster="/assets/bloom/v1/video-poster.webp" aria-label="Bloom Pop Raspberry Lemonade video ad: Only 3g Sugar"><source src="/assets/bloom/v1/showcase.mp4" type="video/mp4"></video></div></div></section>
</div>
<footer class="flyby-bottom"><div class="flyby-progress" id="ad-progress" role="progressbar" aria-label="Connecting to Wi-Fi" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" aria-valuetext="7 seconds remaining"><span aria-hidden="true"></span></div></footer>
</section>`;
}
